### ISSUE TITLE
Load file metadata into database

### ISSUE THREAD

**Issue by weaverba137** [desihub/desispec#51]
Note: the branch 'metadata-db' has been created to address this issue.

We want a metadata database to track the relationships among nights, exposures, bricks and files.  The schema of such a database is described in the file etc/file_db.sql.  We still need code to:

* Register files at file creation time.
* Load a set of files after creation (*i.e.* do the initial population of the database).
* Encapsulate commonly-used queries.

Based on the schema in the file mentioned above, we know how to fill in everything except these columns:

* exposure.telra, exposure.teldec.  These are supposed to be in the pix*.fits files but appear to be missing.
* exposure.tileid.  This should also be in a header somewhere.

**Comment by weaverba137** [comment]
Is there a separate issue already created to address the issues with some missing data related to exposures mentioned above?

**Comment by sbailey** [comment]
I opened [desisim issue 19](https://github.com/desihub/desisim/issues/19) to fix this in the pixel-level simulation output.  That ticket can also be used for any other missing header keywords that we want to fix in the short term.

**Comment by sbailey** [comment]
The discussion of PR #61 raised the issue of how spectro pipeline outputs trace their input provenance.  Currently they don't.  In the future:

* the spectro pipeline planning script could record the dependency chain while putting together the commands to run (this script doesn't yet exist)
* the output files could keep in their header the names of all of their inputs (similar to tracking code versions, also still to be done)
  * this should include the location of the raw data inputs, which crosses out of the production output base directory and into a differently-located raw data input directory.
* both

Discuss.  Let's pick a path and then open a separate issue for implementing that.  My preliminary vote is for "both" even though this does replicate information — each file is standalone for knowing its inputs, while the pipeline planning full chain output could be useful for the big picture.

In the meantime, it seems that the metadata loading script should use `$DESI_SPECTRO_REDUX/$PRODNAME` as the default placeholder for where to find processed data, and `$DESI_SPECTRO_DATA` as the default for where to find the raw data.  Both should be override-able with command line options.  Output should go into `$DESI_SPECTRO_REDUX/$PRODNAME/etc/metadata.db`, even if we're only loading raw data for now.  If we want to have a raw-data-only metadata loading script, let's keep that as a separate thing.

**Comment by weaverba137** [comment]
It's getting toward the end of the day here, so I'll just quickly say two things:

* I also would vote for both, unless it becomes too difficult to manage.
* Which `PRODNAME` should I use for testing purposes for the next round of metadata development.

**Comment by sbailey** [comment]
Current latest is

  * PIXPROD=alpha-5
  * PRODNAME=sjb/dogwood

However, alpha-5 is missing some header keywords (as you noted in the original issue description) and sjb/dogwood is missing input file provenance, so I'm not sure how much further you'll be able to get until that gets sorted out (I'm actively working on it...)

**Comment by weaverba137** [comment]
I can't recall why this is still open.  Can you please check that this has been addressed fully?

**Comment by sbailey** [comment]
the metadatabase code exists, but IIRC it only tracks the metadata for how the raw data are associated with bricks and exposures.  The downstream pipeline still doesn't formally track the input/output dependency tree necessary to load the rest of the database.  In my last comment on this issue I said that I was "actively working on it" which was true at the time but has since gotten derailed by other issues.  Let's keep this issue open since the discussion thread is relevant and the metadata db won't be fully useful until it has the inputs it needs to actually be able to fully load it.

**Comment by weaverba137** [comment]
Based on our discussions at the Director's Review, I'm refactoring this issue into these remaining items.

- Eliminate file tables from the database.
- Track only raw data.
- Add frame table and frame2brick, replacing exposure2brick
- Track status of frames: not-processed, failed, succeeded.
- Track status of bricks.
- Simulate loading the database using DESI tiling defined in desimodel.

Unfortunately I did not photograph the whiteboard after the discussion, so this is based on my raw notes.  Please comment if I've forgotten anything.

**Comment by weaverba137** [comment]
The `raw-data-meta-database` branch contains significant progress on this and will be ready to merge soon.  I have run a simulation of approximately one full year of DESI raw (meta)data, and inserted it into a SQLite database.  This simulation does the following:

1. Assumes 0.5 degree bricks.
2. Uses the `desi-tiles.fits` file to determine pointings.
3. Splits each pointing/tile into ten petal/spectrographs.
4. Determines which bricks overlap a petal/spectrograph.
5. Creates a pre-computed `tile2brick` mapping (technically it is petal2brick, but that's a minor detail).
6. Again starting from the tiles, simulates the metadata for 30 frames associated with each tile, doing this for every tile with `in_desi == 1` and `pass == 1` in `desi-tiles.fits`.  These metadata are loaded into the `frame` table.
7. Uses the pre-computed `tile2brick` mapping to create a `frame2brick` table.
8. Loads a `framestatus` and `brickstatus` table with realistic, yet simplified data.

For the above simulations, the types and magnitudes of all the individual data entries are realistic:

* Integers are integers and have the correct magnitude and sign.
* Telescope pointings are actual RA, Dec.
* Timestamps are realistic and Python-parseable.
* Exposures have a flavor and that flavor is 'science'.
* etc.

So assuming `pass == 1` represents approximately one year, the resulting database is about 90-100 MB depending on whether one cleans out the `tile` and `tile2brick` tables which are only needed by the simulation.  Based on this, if we stuck with SQLite for raw metadata for the whole survey, we'd probably be OK, though it would get ~500 MB by the end of the survey.  For the full survey data challenge, I think it would be fine to use SQLite.

One final step is to ensure that I can still load "real" metadata, *i.e.* parse FITS headers from realistic fibermap files.  For that, @sbailey can you remind me what the latest/best simulation of raw data is?

**Comment by weaverba137** [comment]
I forgot to emphasize: this simulation is based on one exposure per tile.  It *does not* include any calibration exposures (arcs, flats, etc.) or any pointings not associated with a DESI tile.  So the database size needs to be multiplied by a some factor proportional to the ratio of calibration exposures to science exposures.

**Comment by sbailey** [comment]
Thanks for the study.  sqlite seems viable for development work, with likely switching to postgres for the real thing.  We should attempt to keep the schema SQL flavor agnostic so that we can easily switch between them if possible.

The latest test sims are on edison in: /scratch1/scratchdirs/sjbailey/desi/spectro/sim/maple/

**Comment by weaverba137** [comment]
I have successfully loaded metadata from both the maple & madrone simulations.  You can view the resulting databases here:

* /project/projectdirs/desi/spectro/sim/metadata-maple/metadata.db
* /project/projectdirs/desi/spectro/sim/metadata-madrone/metadata.db

One item that is in the schema that can't (yet) be derived from the pix file headers is the telescope altitude and azimuth (alt, az in the `frame` table). I don't remember why that was in there.  If it's important, that should be added to the headers.  If it's not important, it shouldn't be in the database.

**Comment by sbailey** [comment]
OK on alt, az.  They should be included in the raw headers but aren't yet.

Elsewhere in the code we treat night as a string, even though YEARMMDD can be represented as an integer.  I'm not sure we will ever need that flexibility, but elsewhere in the python code it is there.

Looking at maple metadata.db, it appears that tile and tile2brick tables are not filled in.  Unimplemented feature, or bug?

Clarifying scope: is this intended as the structure for just the raw data metadata, or for the processing status too?  IIRC, we had sketched out a minimalist structure for the raw data metadata, with the expectation that that would be copied into a larger per-prod database to keep track of the processing status of a given exposure/tile/brick/etc.  This DB seems to have the processing status tables in there, but the branch name seems to be oriented toward the raw data metadata alone, and I want to make sure we aren't mixing the two, since two different productions could use the same raw data as input and there isn't a unique status from the standpoint of the raw data alone.

**Comment by tskisner** [comment]
I asked a similar question in a comment to the pull request...  Our 
earlier conversations basically proposed copying (and/or updating) the 
raw data database into the production directory and then using that 
copy for production-specific tracking of dependencies and state.  This 
seems like a good idea, but I think we should wait to implement that 
until after the July pipeline milestone.

-Ted

**Comment by weaverba137** [comment]
* I'll add a hook for the code to grab alt, az from the headers if they are there.  *Question*: what exactly will the headers be called, *e.g.* `TELALT`, `TELAZ`?
* I will switch night to be a string.  Better to not break things.
* The `tile` and `tile2brick` tables are only needed for the simulations.  Since the fibermap file contains a list of bricks, it is not necessary to compute the overlap of tiles and bricks.
* I think Ted addressed the scope question.

**Comment by sbailey** [comment]
alt/az: [DESI-1229](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=1229) is a spreadsheet with Klaus' intended keywords, but those don't include any variation of alt/az that I can see.  I think we should request that, and either ALT, AZ or TELALT TELAZ seems reasonable.  That doc includes both TELRA and RA, but doesn't explain their difference.  Presumably if they have a difference then we might have both ALT/AZ and TELALT/TELAZ to match.  In principle these are derivable from RA, DEC and DATE-OBS, but in practice that is also dependent upon the exact atmospheric dispersion model and it might be convenient to include them in the header too.  Pick something and load it if the keyword is there, but don't let this be a blocking factor.

tile and tile2brick: "only needed for the simulations" -- do you mean the scaling tests of loading up the DB?  Or do you mean our data simulations or something else?  If we don't need it for the real data, then we shouldn't need it for the simulations of the data.  Even for the real data, it could be handy to have that mapping pre-calculated, but it could be lower priority for implementation if it isn't otherwise already needed.  But I'm not sure I understand what you meant.

**Comment by weaverba137** [comment]
By "only needed for simulations", I specifically mean the DB loading scaling tests.  I can certainly include it by default though.  I think it adds about 10 MB to the database.  Basically, though, if the fibermap files already tell you what bricks are in the exposure, you don't need the tile table.
