### ISSUE TITLE
Step-like troughs at arm transitions

### ISSUE THREAD

**Issue by nathalieGit** [desihub/desispec#929]
Seen in tile 68001, here are some spectra showing a step-like trough, often around the blue/red arm transition

![Screenshot 2020-03-21 at 19 43 21](https://user-images.githubusercontent.com/16261908/77234176-b2691700-6bac-11ea-80d3-d284a2e68203.png)
![Screenshot 2020-03-21 at 19 42 07](https://user-images.githubusercontent.com/16261908/77234183-bb59e880-6bac-11ea-97e4-aabd0f1056cd.png)
![Screenshot 2020-03-21 at 19 43 13](https://user-images.githubusercontent.com/16261908/77234189-be54d900-6bac-11ea-9bfc-9afbdc2388cd.png)

**Comment by nathalieGit** [comment]
Oops, I forgot to attach the list of relevant targetIDs exhibiting this problem. Here it is.

**Comment by nathalieGit** [comment]
OOps, forgot to add the file with relevant targetIDs

**Comment by nathalieGit** [comment]
35191259366689210,35191263049286971,35191263053482382,35191266710914407,35191266719304869,35191270347375792,35191270359958816,35191277582550402,35191288223501412,35191281172874476,35191284729644198

**Comment by julienguy** [comment]
the first one is likely the same issue as #922

**Comment by julienguy** [comment]
others are due to over subtraction of the sky spectrum. 
```
plot_spectra -i /global/cfs/cdirs/desi/spectro/redux/daily/tiles/68001/20200315/coadd-2-68001-20200315.fits --targetid 35191263049286971 --rebin 4

plot_frame -i /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20200315/*/{s,}frame-r2-000556{11,12,13}.fits --fibers 1380 --legend --rebin 8
```

![Screenshot from 2020-03-23 14-20-55](https://user-images.githubusercontent.com/5192160/77364554-d003c100-6d11-11ea-873e-3385bcb6bc72.png)

**Comment by sbailey** [comment]
The remaining problems with sky subtraction are more subtle.  Taking this off the critical path for 20.4 rerun, but recheck after that rerun because we have also improved the calibrations which may have fixed this.  After that we can reassess.

**Comment by kdawson1000** [comment]
To help test whether the change in sky subtraction is improving this feature, here are a few more examples that I found in the LRG spectra on tile 68002.  The first part of this list all occur around 5800 AA.  I think the problem lies on the blue end of the middle camera, near the dichroic region.

35185923939372506
35185929941421564
35185935935079658
35185941920352721
35185941920352849
35185941920352911
35185941924548284
35185941924548708
35185941953904787
35185947914013516
35185947914013986
35185947914014954
35185947918205618
35185947918206371
35185947918208995
35185947918209291
35185941958101763
35185941958102700
35185941962295697
35185941962296996
35185941962297871
35185941953908969
35185947934984501
35185953903479132
35185953903479976
35185953903480105
35185953907675218
35185953911865829
35185953911865973
35185953911869231
35185947951764195
35185947955955603
35185947955958224
35185953916062898
35185953932839515
35185953945423444
35185959892943534
35185959892943603
35185959892944152
35185959892944545


There were also a few residuals that appeared in a different wavelength region:
35185935926693820
35185935930884346
35185959897141820 -- telluric?
35185965865631802 -- telluric?
35185965869829025 -- problem at 6700 AA
35185965869829500 -- telluric?
35185965878215754 -- telluric?
35185965886604776 -- over range 6800-7600 AA

**Comment by julienguy** [comment]
Hi @kdawson1000 aka Kyle, can you please specify which file on disk at nersc this data corresponds to? This would solve any potential ambiguity on software/data release version or range of exposures contributing to the coadd. It would also make it easier for us to look at the problematic data.

**Comment by julienguy** [comment]
After a chat with Kyle, spectra from:
```
/global/project/projectdirs/desi/spectro/redux/daily/tiles/68002/20200315/
```

**Comment by julienguy** [comment]
The bad sky subtraction reported by Nathalie ( @nathalieGit ) were due to the glow in SM5 SP2 RED CCD. Part of the glow was in the sky model which resulted in an overestimated sky model, and negative sky residuals. This was fixed in Andes because the whole quadrant had a weight=0 in the sky model fit.
See for instance
```
plot_frame -i /global/cfs/cdirs/desi/spectro/redux/andes/exposures/20200315/*/sframe-r2-000556{11,12,13}.fits --fibers 1380 --legend --rebin 8
```

A majority of the targets reported by Kyle are also in SP2 (=SM5), but not all of them. So it's not the same cause for all spectra.
The "step" between the blue and red cameras for faint targets is still there. It could be due to a bias+dark subtraction issue. 

```
plot_spectra -i /global/project/projectdirs/desi/spectro/redux/jguy/tiles/68002/20200315/coadd-0-68002-20200315.fits  -t 35185923939372506 --rebin 16
```
![Screenshot from 2020-10-28 16-06-12](https://user-images.githubusercontent.com/5192160/97506304-d907e100-1937-11eb-9203-31a6fba0563d.png)

Not all spectra have visible issues though ... (?)

```
plot_spectra -i /global/project/projectdirs/desi/spectro/redux/jguy/tiles/68002/20200315/coadd-0-68002-20200315.fits  -t  35185929941421564 --rebin 16
```

![Screenshot from 2020-10-28 16-20-17](https://user-images.githubusercontent.com/5192160/97507031-8deecd80-1939-11eb-831a-a8f24d9c3662.png)

**Comment by sbailey** [comment]
I re-inspected all of the targets from Kyle's list from night 20200315 tile 68002 on the blanc release.  Although many of them are now better, problems remain:

68002-20200315-sp0: 35185947934984501

68002-20200315-sp1: 35185935935079658

68002-20200315-sp2: many
35185941920352721, 35185941920352849, 35185941920352911,
       35185941924548284, 35185941924548708, 35185947914013516,
       35185947914013986, 35185947914014954, 35185947918205618,
       35185947918206371, 35185947918208995, 35185947918209291,
       35185953903479132, 35185953903479976, 35185953903480105,
       35185953907675218, 35185953911865829, 35185953911865973,
       35185953911869231, 35185953916062898, 35185959892943534,
       35185959892943603, 35185959892944152, 35185959892944545

68002-20200315-sp8 : sharp features at B:R dichroic
35185941962295697, 35185947955955603, 35185941958102700, 35185953932839515

68002-20200315-sp8 : steps features at B:R dichroic
35185953945423444, 35185941962297871, 35185941962296996, 35185941962295697, 35185947951764195

68002-20200315-sp9 : 35185941953904787, 35185941953908969, 35185941953904787

This tile was observed on exposures 55626-28 on 20200315, and in most cases the problems are consistent between different exposures.

Selected screenshots from sp8:

![image](https://user-images.githubusercontent.com/218471/104513425-7cb27600-55a4-11eb-8416-d18865d0d917.png)
![image](https://user-images.githubusercontent.com/218471/104513446-8936ce80-55a4-11eb-918e-d17f2c8b7d95.png)

Code snippet for jupyter at NERSC with a DESI 20.12 (or master) kernel:
```
import os, sys, glob
import numpy as np
import desispec.io
from astropy.table import Table
prospectpath = '/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/prospect/master/py'
if prospectpath not in sys.path:
    sys.path.append(prospectpath)
import prospect.plotframes

targetids = np.array([
35185941962295697,
35185947955955603,
35185941958102700,
35185953932839515,
35185953945423444,
35185941962297871,
35185941962296996,
35185941962295697,
35185947951764195,
])

sp = 8
tileid, night = 68002, 20200315
reduxdir = '/global/cfs/cdirs/desi/spectro/redux/blanc'
specfile = f'{reduxdir}/tiles/{tileid}/{night}/spectra-{sp}-{tileid}-{night}.fits'
spectra = desispec.io.read_spectra(specfile)
spx = spectra.select(targets=targetids)
prospect.plotframes.plotspectra(spx, notebook=True)
